### ISSUE TITLE
void-installer: fails to install grub if /boot is a separate partition

### ISSUE THREAD

**Issue by pullmoll** [void-ppc/void-mklive#1]
So I tried to install using the current ISO on my G5. It currently has 1TB HDD which contained a 80GB Mac OS X installation in part3. I deleted part2 (127.5M free) and created the bootstrap partition with "C 2p 10M bootstrap Apple_Bootstrap" and also created some more partitions giving me this layout:

+ 1p 31.5k partition table
+ 2p 10.0M hfs (/boot/apple_bootstrap)
+ 3p 118.0M Apple_Free
+ 4p 80.0G Apple_HFS (Mac OS X)
+ 5p 8.0G swap
+ 6p 1.0G ext2 boot (/boot)
+ 7p 32.0G ext4 void (/)
+ 8p 32.0G ext4 var (/var)
+ 9p 240.0G ext4 home (/home)
+ 10p 538.4G Free Space

Now I chose local installation and everything went fine until `grub-install` told it couldn't find the `/boot/apple_bootstrap` partition. The reason for the failure is that the mount point `/boot/apple_bootstrap` was created on the void `/` partition and not on the `/boot`  partition. I think this is due to how mount points are created and sorted by the order of partitions, not by the path name strings.

The easy solution probably is to not use a separate boot (/boot) partition at all. OTOH this is how many (x86) people are used to setup their systems. It should also be possible to avoid this problem by using e.g. `/.apple_bootstrap` as the mount point for the HFS partition while I don't know if this is a *Good Idea (tm)*.

**Comment by q66** [comment]
Also, I was able to confirm that it is in fact not possible to boot OS Xfrom GRUB. However, fi you have a blessed boostrap partition with GRUB, and a blessed HFS+ partition with OS X, you should be able to hold Option during boot and choose which partition to boot from.

**Comment by q66** [comment]
Closing this as this issue has long been solved.
