### ISSUE TITLE
live USB may fail to boot out of box on PowerPC Macs

### ISSUE THREAD

**Issue by q66** [void-ppc/void-mklive#2]
On my PowerMac G5 11,2 (late 2005), using the `ppc64` live image dd'd onto a USB flash disk fails to boot out of box. After using `boot ud:,\\:tbxi` from the OpenFirmware prompt, GRUB comes up and upon selection of the right boot option, the Linux kernel loads, however, the initramfs fails to mount the USB flashdisk when looking for the `squashfs`.

For the kernel, `/dev/sdb` is the live flash disk; the message that comes up on the screen is like this:

```
mount: /run/initramfs/live: wrong fs type, bad option, bad superblock on /dev/sdb1, missing codepage or helper program, or other error.
dracut: FATAL: Failed to mount block device of live image
dracut: Refusing to continue
```

After a while, I'm dropped into the Dracut recovery shell.

I looked around why that may be, and found that within the initial initramfs environment, the partition layout for `/dev/sdb` looks like this:

```
/dev/sdb (14.4GB, iso9660)
- /dev/sdb1 (200MB, filesystem unknown, label=VOID_LIVE)
- /dev/sdb2 (14.2GB, filesystem unknown)
```

The GRUB menu entry passes `root=live:CDLABEL=VOID_LIVE`. In the dracut environment, `/dev/disk/by-label/VOID_LIVE` points to `/dev/sdb1` which is not mountable. However, `/dev/sdb` itself is mountable as `iso9660`.

Once booted past initramfs, the layout suddenly looks like this:

```
/dev/sdb (14.4GB)
- /dev/sdb1 (14.4GB, iso9660, label=VOID_LIVE)
```

`/dev/sdb1` is normally mountable then, as is `/dev/sdb`. This is also the behavior I see on any other computer I tried, and also the behavior within the initramfs in `qemu` (when booting the ISO as a disk).

I'm not quite sure what the reason or the solution is. I suspect it has something to do with the hybrid APM layout of the ISO image, with the flash drive getting represented as an Apple partition layout with two partitions for whatever reason. Maybe @pullmoll or @stenstorp have some clues. Or maybe @awilfox if they ever ran into something similar with Adélie.

# Workaround for users

This issue can easily be worked around, so the severity is not huge, but we should figure it out anyway. When the error message comes up, take note of which device failed to mount.

Then, reboot and when you're in GRUB, use the `e` key to edit the menu entry. Then, on kernel command line, change `root=live:CDLABEL=VOID_LIVE` to e.g. `root=live:/dev/sdb` (if `sdb1` was the failed partition).

The system should come up normally then, because it will try to mount `/dev/sdb` directly instead of `/dev/disk/by-label/VOID_LIVE` which is really `/dev/sdb1`.

**Comment by pullmoll** [comment]
The problem seems to be due to the label for `/dev/sdb1` overwriting the label for `/dev/sdb` in `/dev/disk/by-label`. So perhaps this can be fixed in `eudev` in some way, e.g. by choosing a different name in case the label name already exists? If udev would create `/dev/disk/by-label/VOID_LIVE_1 -> /dev/sdb1` this should solve the problem.

**Comment by q66** [comment]
well i'm more curious about what is the exact reason it shows up as two partitions in the initramfs environment and as one partition in the booted environment, and why it happens only on that powermac...

**Comment by pullmoll** [comment]
Perhaps you can save the content of `/dev/sdb1` on the HDD to inspect what is in there, or can this be seen in the ISO image itself? IIRC booting from USB worked here be it with my homegrown ISOs and linux-4.19.5x the last time I tried.

**Comment by q66** [comment]
Dunno, I'll look into it again when I have time, once I have some fresh ISOs again (with 5.1 kernel). This could also be easily patched in dracut, but I'd rather find the root cause than patching the symptoms :)

**Comment by q66** [comment]
This is not reproducible anymore with fresh ISOs with kernel 5.1.
