### ISSUE TITLE
Missing PATA kernel drivers/modules in the live image? Mac mini G4

### ISSUE THREAD

**Issue by truscellino** [void-ppc/void-mklive#5]
Hi,
I was very excited to find out about void linux PPC. I tried an install on a mac mini G4 but unfortunately the internal PATA drive is not visible from the live session. I wonder if some kernel drivers are missing from the live CD?
The internal drive is fine under Os X 10.4 and is also visible if I boot on an old Gentoo PPC minimal install CD. In that case, kernel (3.10) drivers in use are: macio and ide-pmac for this UniNorth/Intrepid I/O.
Thanks

**Comment by q66** [comment]
Interesting. It seems to mostly work on PowerBooks and iBooks. Might be one of those cases where support is only covered in the legacy drivers. I guess we should be able to enable that for our kernel configs

**Comment by truscellino** [comment]
OK thanks. I am happy to do some testing if there is an opportunity.

**Comment by q66** [comment]
there's now a fresh batch available, feel free to give that a test.

**Comment by truscellino** [comment]
I can confirm that voidlinux-ppc live (11 April iso musl image) can detect the drive when booting with kernel 4.4, but NOT with kernel 5.4 with which it falls back to Dracut shell. I suspect a kernel regression problem already identified, but haven't finished to investigate.

**Comment by q66** [comment]
yes, i had another person with a mac mini confirm that the 5.4 kernel works on theirs (fwiw, the 4.4 config is derived from the 5.4 one), which means you have a model of a mini where this regressed. I disabled the legacy drivers in the kernels again, and changed the configuration to make IDE builtin, maybe it's just a detection issue. Even if it isn't, it's probably best to make it builtin, it doesn't add much to size and vast majority of machines the kernel will be booted on will be macs with IDE, and this will allow for initramfs-less boot and so on.

anyway, I suggest you use a kernel version that works for you for now; you have a choice of 4.4, 4.9, 4.14, 4.19, 5.4, 5.5 and 5.6, one or more of them should work :)

**Comment by q66** [comment]
Kernel issues should be taken to upstream, also on some G4 minis it works (including mine, that I got for testing this)

as a workaround the current ISOs are all dual-kernel, so closing

**Comment by truscellino** [comment]
Yes sorry I should have replied before. void-ppc works fine on Mac Mini G4 with kernels up to 4.9. Definitely an issue with libata from 4.11 onwards. Thanks
